### ISSUE TITLE
Waiting for '/controller_manager' node to exist

### ISSUE THREAD

**Issue by srwhite1995** [ICube-Robotics/iiwa_ros2#20]
Hi,

Thanks for creating this project. I am trying to use it, however when I run it, the /controller_manager node never fires up, this eventually causes an error:

 Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in ./src/buffer_core.cpp

Rviz eventually loads, but it displays a white box disconnected from the iiwa base.

Any ideas of what might cause this?

Many thanks,
Sam

**Comment by mcbed** [comment]
Hi, in which context are you running the driver ? If you are using the real robot, make sure the FRI communication is running. If not, the robot will not send its current state resulting in what you have.

**Comment by srwhite1995** [comment]
Hi, at the moment I am just trying to simulate the arm. I will test it on the real arm tomorrow and let you know the outcome. It is possible, that this is a simulation error. Will confirm. Many thanks, Sam

**Comment by srwhite1995** [comment]
[
![image](https://user-images.githubusercontent.com/103044188/185787272-71fe377f-1b37-4122-86fb-4c03106475a1.png)
](url)

**Comment by mcbed** [comment]
Hi, can you also tell me what is the command your are running to have this outcome?

**Comment by srwhite1995** [comment]
I am running ros2 launch iiwa_bringup iiwa.launch.py use_sim:="true"

**Comment by mcbed** [comment]
Ok, in this case, do you have a gazebo simulation running ? Also make sure you pull the latest version of the repo.

**Comment by srwhite1995** [comment]
For some reason, gazebo does not trigger. I will investigate why. What I wanted to do, it try to program it with the moveit commands and just visualise in rviz. I can get the model loaded in if I set planning to be true, but it will not make the motions, I believe owing to its inability to find the controller manager.

any planning always fails, as shown by this screenshot.

Many thanks,
Sam[
![image](https://user-images.githubusercontent.com/103044188/185794028-2326cab1-6360-4b79-9c92-f7ad646d6160.png)
](url)

**Comment by mcbed** [comment]
This is normal if you did not launch gazebo properly. See #4 for some debug hints. If the gazebo plugin is not started properly, the controller manager is not available, thus not further nodes can work as expected.

**Comment by mcbed** [comment]
Also, if you want a simple simulation without gazebo consider running `iiwa.launch.py` without any arguments

**Comment by srwhite1995** [comment]
When I run it without any arguments it still does not work, producing the same errors :(

**Comment by srwhite1995** [comment]
Does this rqt_graph look sensible?

![image](https://user-images.githubusercontent.com/103044188/185796881-206aa5e2-72e8-489c-9302-bd3c81e16020.png)

**Comment by mcbed** [comment]
Can you print the full log from the terminal to get a better insight ?

**Comment by srwhite1995** [comment]
[INFO] [launch]: All log files can be found below /home/kuka/.ros/log/2022-08-21-16-35-31-676675-kuka-DQ67SW-58222
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_control_node-1]: process started with pid [58254]
[INFO] [robot_state_publisher-2]: process started with pid [58256]
[INFO] [spawner-3]: process started with pid [58258]
[INFO] [spawner-4]: process started with pid [58260]
[robot_state_publisher-2] Link iiwa_base had 1 children
[robot_state_publisher-2] Link link_0 had 1 children
[robot_state_publisher-2] Link link_1 had 1 children
[robot_state_publisher-2] Link link_2 had 1 children
[robot_state_publisher-2] Link link_3 had 1 children
[robot_state_publisher-2] Link link_4 had 1 children
[robot_state_publisher-2] Link link_5 had 1 children
[robot_state_publisher-2] Link link_6 had 1 children
[robot_state_publisher-2] Link link_7 had 1 children
[robot_state_publisher-2] Link tool0 had 0 children
[robot_state_publisher-2] [INFO] [1661096133.448538049] [robot_state_publisher]: got segment iiwa_base
[robot_state_publisher-2] [INFO] [1661096133.448759222] [robot_state_publisher]: got segment link_0
[robot_state_publisher-2] [INFO] [1661096133.448788807] [robot_state_publisher]: got segment link_1
[robot_state_publisher-2] [INFO] [1661096133.448810348] [robot_state_publisher]: got segment link_2
[robot_state_publisher-2] [INFO] [1661096133.448830593] [robot_state_publisher]: got segment link_3
[robot_state_publisher-2] [INFO] [1661096133.448849975] [robot_state_publisher]: got segment link_4
[robot_state_publisher-2] [INFO] [1661096133.448869379] [robot_state_publisher]: got segment link_5
[robot_state_publisher-2] [INFO] [1661096133.448888449] [robot_state_publisher]: got segment link_6
[robot_state_publisher-2] [INFO] [1661096133.448908002] [robot_state_publisher]: got segment link_7
[robot_state_publisher-2] [INFO] [1661096133.448926822] [robot_state_publisher]: got segment tool0
[robot_state_publisher-2] [INFO] [1661096133.448945893] [robot_state_publisher]: got segment world
[ros2_control_node-1] [INFO] [1661096133.547167331] [resource_manager]: Loading hardware 'iiwaRobot' 
[ros2_control_node-1] terminate called after throwing an instance of 'pluginlib::CreateClassException'
[ros2_control_node-1]   what():  MultiLibraryClassLoader: Could not create class of type fake_components::GenericSystem
[ERROR] [ros2_control_node-1]: process has died [pid 58254, exit code -6, cmd '/home/kuka/ros2_humble/install/controller_manager/lib/controller_manager/ros2_control_node --ros-args -r __ns:=/ --params-file /tmp/launch_params_fw42rq6g --params-file /home/kuka/ros2_humble/install/iiwa_description/share/iiwa_description/config/iiwa_controllers.yaml'].
[spawner-3] [INFO] [1661096135.016517198] [spawner_ets_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1661096135.022543265] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1661096137.039432797] [spawner_ets_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1661096137.043270796] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1661096139.069721269] [spawner_ets_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1661096139.069721259] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1661096141.107720440] [spawner_ets_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1661096141.107720352] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1661096143.146056969] [spawner_ets_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1661096143.146056943] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [ERROR] [1661096144.971324819] [spawner_ets_state_broadcaster]: Controller manager not available
[ERROR] [spawner-3]: process has died [pid 58258, exit code 1, cmd '/home/kuka/ros2_humble/install/controller_manager/lib/controller_manager/spawner ets_state_broadcaster --controller-manager /controller_manager --ros-args'].
[spawner-4] [ERROR] [1661096145.173781208] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-4]: process has died [pid 58260, exit code 1, cmd '/home/kuka/ros2_humble/install/controller_manager/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-2] [INFO] [1661096145.778873240] [rclcpp]: signal_handler(signum=2)
[INFO] [spawner-5]: process started with pid [58360]
[INFO] [robot_state_publisher-2]: process has finished cleanly [pid 58256]
[spawner-5] [INFO] [1661096146.569803195] [spawner_iiwa_arm_controller]: Waiting for '/controller_manager' node to exist
[spawner-5] [INFO] [1661096148.593284854] [spawner_iiwa_arm_controller]: Waiting for '/controller_manager' node to exist
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT) again, ignoring...


Above is how it begins. I interrupted to avoid this part being lost in the terminal. After rviz loads, I get;
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-2] [INFO] [1661096241.202899226] [rclcpp]: signal_handler(signum=2)
[rviz2-6] [INFO] [1661096241.202908557] [rclcpp]: signal_handler(signum=2)
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_1" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_2" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_3" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_4" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_5" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 93 in /home/kuka/ros2_humble/src/ros2/geometry2/tf2/src/buffer_core.cpp
[rviz2-6] Warning: Invalid frame ID "link_6" passed to canTransform argument source_frame - frame does not exist
 endlessly

**Comment by mcbed** [comment]
This is the bug : [resource_manager]: Loading hardware 'iiwaRobot'
[ros2_control_node-1] terminate called after throwing an instance of 'pluginlib::CreateClassException'
[ros2_control_node-1] what(): MultiLibraryClassLoader: Could not create class of type fake_components::GenericSystem

There has been a recent change in ros2 control renaming `FakeComponent` to `MockComponent` which is the source of the error here. It was probably put into the release binaries recently. I will make the fixe when I have some time.

**Comment by srwhite1995** [comment]
OK, thank you for letting me know. Can I investigate the fix for you? Where would FakeComponent and MockComponent be used in your package? Many thanks!

**Comment by mcbed** [comment]
You need to start from [here](https://github.com/ICube-Robotics/iiwa_ros2/blob/aae159475d99c231456e34fd786eca40fcc5f16c/iiwa_description/ros2_control/iiwa.r2c_hardware.xacro#L17). Any help is welcome!

**Comment by srwhite1995** [comment]
Great, thank you! I will investigate for you and fork the repo. Is it likely to not be a problem when connected to the real robot?

**Comment by mcbed** [comment]
It is just a simulation component that run instead of the robot driver and is not launched if you run the real robot.

**Comment by srwhite1995** [comment]
An update:

On the real robot the launcher gets stuck on:

[spawner-3] [INFO] [1661173271.322444319] [spawner_ets_state_broadcaster]: Waiting for '/controller_manager' node to exist

**Comment by mcbed** [comment]
In this case, I think you are missing some ros2_control dependencies. After some tests on my side even the depreciated `FakeComponent` should be able to run with some warning.
