### ISSUE TITLE
Install Problem - fresh install

### ISSUE THREAD

**Issue by MightyMirko** [ICube-Robotics/iiwa_ros2#21]
Hello

Description

ROS Distro: Galactic
OS Version: e.g. Ubuntu 20.04

Steps to reproduce

```

cd ~/ros2_ws
git clone https://github.com/ICube-Robotics/iiwa_ros2.git src/iiwa_ros2
rosdep install --ignore-src --from-paths . -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install
source install/setup.bash


```

Expected Behaviour:

Install without fail:
https://gist.github.com/MightyMirko/229f3a0f5d809c8acd42315a117d4362

I also had to install ros-control manually. I'd like to contribute but have to dig deeper in dependencies to be sure

**Comment by MightyMirko** [comment]
Also had to upgrade cmake to higher than 3.21
https://www.linuxfordevices.com/tutorials/install-cmake-on-linux#For-UbuntuDebian-and-their-derivatives
`
cmake --version
$ wget https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.sh -O cmake.sh
sudo sh cmake.sh --prefix=/usr/local/ --exclude-subdir
cmake --version`

**Comment by MightyMirko** [comment]
Hmm perhaps i've done something wrong - i deleted the workspace and tried again 
```

git clone https://github.com/ICube-Robotics/iiwa_ros2.git src/iiwa_ros2 -b galactic
rosdep install --ignore-src --from-paths . -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install
```
= 
https://gist.github.com/MightyMirko/a85e1d8c7c0ee9bd8f68f9fd72e92ab9

**Comment by MightyMirko** [comment]
I had done things wrong with ros2-controllers .. it was also in my workspace which should not have been there

**Comment by MightyMirko** [comment]
```
mirko@s25v-ubu2004-ros2-gui:~/iiwa_ros2ws$ ros2 launch iiwa_bringup iiwa_test_joint_trajectory_cont
roller.launch.py
[INFO] [launch]: All log files can be found below /home/mirko/.ros/log/2022-09-08-15-07-15-319821-s
25v-ubu2004-ros2-gui-3758
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt
/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=PackageNotFoundEr
ror("package 'ros2_control_test_nodes' not found, searching: ['/home/mirko/iiwa_ros2ws/install/impe
dance_controller', '/home/mirko/iiwa_ros2ws/install/iiwa_moveit2', '/home/mirko/iiwa_ros2ws/install
/iiwa_hardware', '/home/mirko/iiwa_ros2ws/install/iiwa_bringup', '/home/mirko/iiwa_ros2ws/install/i
iwa_description', '/home/mirko/iiwa_ros2ws/install/external_torque_sensor_broadcaster', '/opt/ros/g
alactic']")>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in
get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in
 get_resource
    raise LookupError(
LookupError: Could not find the resource 'ros2_control_test_nodes' of type 'packages'

```

`ros-galactic-ros2-controllers-test-nodes ist schon die neueste Version (1.4.0-1focal.20220730.021749).
`


it seems to be installed but iam still getting error :-(

**Comment by mcbed** [comment]
hi, did you download and source the [ros2_control_demos](https://github.com/ros-controls/ros2_control_demos) package which is a dependency here ? 
Also, make sure you use the galactic branch of the repository as the main branch was ported to humble.
