### ISSUE TITLE
servoing jerkiness

### ISSUE THREAD

**Issue by alandelira** [ICube-Robotics/iiwa_ros2#22]
I am using the joy_servo_teleop.launch.py example with a game controller. The iiwa moves however the movement is very jittery. I tried changing the publish_period in iiwa_moveit2_servo_config.yaml and it helped a little, but the motion is still jerky.

Any recommendations? Were you using a real time kernal? I would be glad to provide more details about my setup.

Thank you.

**Comment by mcbed** [comment]
Hi, we had the same issue when using the `joint_trajectory_controller` to do velocity control. What we did is to rather send velocity commands to the velocity controller resulting in a smooth motion. If, however, someone knows what could cause the issue I would very much like to have some feedback.

**Comment by MyZQL** [comment]
We meet the same problem on iiwa7. Has anyone solved it? I suspect that there is something wrong when combining MoveitServo and FRI.

**Comment by dave-cliftonphotonics** [comment]
i also have this problem
