### ISSUE TITLE
Planning with moveit2 tutorial hello_moveit fails

### ISSUE THREAD

**Issue by eyal-friedman** [ICube-Robotics/iiwa_ros2#27]
In the last few days, I've been trying to control the arm with Moveit2 following the Moveit2 tutorials, and I'm failing with the demo node example to connect to the planning engine.

I realized that I should add to the 'Ros param' the options:
ros__parameters:
    #use_sim_time: True
    publish_robot_description: True
    publish_robot_description_semantic: True
To speculate it to the planning node.

After doing so, I still can't make it work. 
While running the Hello_moveit2 node I get the message:
[INFO] [1669134673.662537690] [move_group_interface]: MoveGroup action client/server ready
[INFO] [1669134674.065487066] [move_group_interface]: Planning request accepted
[INFO] [1669134674.166100159] [move_group_interface]: Planning request aborted
[ERROR] [1669134674.266322450] [move_group_interface]: MoveGroupInterface::plan() failed or timeout reached
[ERROR] [1669134674.266431050] [hello_moveit]: Planing failed!

And in the main thread I receive the:
[move_group-3] [INFO] [1669134673.664465904] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[move_group-3] [INFO] [1669134673.664998807] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[move_group-3] [INFO] [1669134673.665266209] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[move_group-3] [ERROR] [1669134673.665484611] [moveit.pilz_industrial_motion_planner]: No ContextLoader for planner_id '' found. Planning not possible.
[move_group-3] [INFO] [1669134673.665553511] [moveit_move_group_default_capabilities.move_action_capability]: Unknown event

Any ideas?
Thanks

**Comment by mcbed** [comment]
Hi, 
Your question is more related to Moveit2 than to the iiwa_ros2, so you should rather ask there. 
However, from your log, it looks as if you are trying to plan using Pilz planning pipeline without specifying the planner id. Also,  by default, Moveit2 tutorials use OMPL planning pipelines, which could be the origin of your issue.
