### ISSUE TITLE
impedance_controller usage

### ISSUE THREAD

**Issue by puyilin** [ICube-Robotics/iiwa_ros2#31]
Hello, master. I want to use the impedance_controller to get some work done, so I ran command_interface:="effort" robot_controller:="impedance_controller" to load impedance_controller, but I don't know how to make the robot move with impedance_controller, could you give me some tips?

**Comment by mcbed** [comment]
Hi @puyilin, the impedance controller from this stack takes as input `trajectory_msgs::msg::JointTrajectory` and generates the corresponding effort based on the [impedance parameters](https://github.com/ICube-Robotics/iiwa_ros2/blob/eeb7608f60550b84ad97a1c520a686edb2b2baea/iiwa_description/config/iiwa_controllers.yaml#L60) of the controller. 
To make your robot move you need to publish such a trajectory message on the `/proxy` topic. Just be aware that the effort is proportional to the distance between your current position and the target proxy, so if the proxy is too far, high effort commands will be generated.

**Comment by puyilin** [comment]
> Hi @puyilin, the impedance controller from this stack takes as input `trajectory_msgs::msg::JointTrajectory` and generates the corresponding effort based on the [impedance parameters](https://github.com/ICube-Robotics/iiwa_ros2/blob/eeb7608f60550b84ad97a1c520a686edb2b2baea/iiwa_description/config/iiwa_controllers.yaml#L60) of the controller. To make your robot move you need to publish such a trajectory message on the `/proxy` topic. Just be aware that the effort is proportional to the distance between your current position and the target proxy, so if the proxy is too far, high effort commands will be generated.

Thanks for your reply. I published the target position on /proxy topic ,it did work. I want to know could the impedance_controller be used in moveit2 like iiwa_arm_controller? I noticed iiwa_arm_controller in iiwa_description/moveit2/iiwa_controller_names.yaml and iiwa_moveit_controller_config.yaml.

**Comment by mcbed** [comment]
@puyilin, not directly as it does not interpolate trajectory setpoints. One way would be to expand the controller to support controller chaining features from ros2_control.

**Comment by puyilin** [comment]
ok, thanks for your reply
