### ISSUE TITLE
[How-To] How to start coding own software

### ISSUE THREAD

**Issue by MightyMirko** [ICube-Robotics/iiwa_ros2#33]
Hello, 

i'd like to write my own publishing node for angles or cartesian positions but i dont know how and where to start. 

My goal is to mount a camera on the iiwa7 and track a moving qr code or aruco tag. The detection is almost done and now i'd like to publish and transform the pose of the tag to iiwa to follow the tag with movements. 

Where should i start? 

#5 #32

**Comment by mcbed** [comment]
Hi @MightyMirko, 
To send Cartesian targets to the robot you need to use [Moveit2](https://moveit.picknik.ai/humble/index.html). You can do this by starting the launch file with the flag `use_planning:=true`. 
Also I saw you are using `foxy` which does not work very well, I suggest you consider switching to `humble`.

**Comment by MightyMirko** [comment]
Hello @mcbed, doing the installation right now - ill test it and like to use this thread as a howto in the next couple of week :-)

**Comment by MightyMirko** [comment]
Finally i had some time to go for it again. Now everything is running well and i can move the robot in rviz, pilz planner and drag it around. I want to write a node which takes the current joint states, do some calculation and move the robot around. 
What would be a good starting point?
