### ISSUE TITLE
Sunrise Connectivity.FRI version?

### ISSUE THREAD

**Issue by dmronga** [ICube-Robotics/iiwa_ros2#37]
Dear maintainers, I was wondering if you could document the FRI version used to test the ROS2 stack. I am using Sunrise Connectivity 1.7 and it seems to be incompatible. What is the minimum FRI / Connectivity version required?
Best regards

**Comment by Odin-byte** [comment]
Did you find the error or the correct version of FRI?

Because I might have stumbled across the same issue as I can not connect to the UDP server or even ping the robot, while all addresses are set up according to the README.

**Comment by dmronga** [comment]
Sorry for the late reply, the driver works for me with Connectivity 1.7. Previously, I did not have connection problems, but rather compilation errors. I had to rename some imported Java modules in iiwa_ros2.java, e.g., 
`
import com.kuka.connectivity.fastRobotInterface.FRIChannelInformation;
`

rename to

`
import com.kuka.connectivity.fri.FRIChannelInformation;
`

and do some minor code changes.
