### ISSUE TITLE
about "Example commands for setup testing"

### ISSUE THREAD

**Issue by puyilin** [ICube-Robotics/iiwa_ros2#9]
from this example, i know how to causes the arm joint to move to a specified angle, but now i want to know if i could make the end of the arm move to a given coordinates?

**Comment by mcbed** [comment]
To do so you need to compute the robot inverse kinematics. You can consider using tools like Moveit2 as the robot is redundant.

**Comment by puyilin** [comment]
> To do so you need to compute the robot inverse kinematics. You can consider using tools like Moveit2 as the robot is redundant. 

Thank you for your answer, i will have a try.
